import Dashboard from "@/components/Dashboard";
import Main from "@/components/Main";

export const metadata = {
    title: "Broodl ⋅ Dashboard",
    description: "Generated by create next app",
};

const DashboardPage = () => {

    const isAunthenticated = false;

    const children = (
        <Dashboard/>
    )

    return(
        <Main>
            {children}
        </Main>
    )
}  

export default DashboardPage;